import {test} from 'node:test';
import assert from 'node:assert/strict';
import {PILOT_HEADERS,parsePilotCSV,summarizePilot} from '../src/pilot-metrics.mjs';
const observation=(id,extra={})=>Object.fromEntries(PILOT_HEADERS.map(h=>[h,({participant_id:id,variant:'adaptive',adult_confirmed:'yes',consent_recorded:'yes',pre_source:'1',pre_year:'0',pre_deadline:'0',post_source:'1',post_year:'1',post_deadline:'1',completed:'yes',duration_seconds:'600',clarity_1_5:'4',help_requests:'0',...extra})[h]]));
test('a blank study has no invented results',()=>{const s=summarizePilot(parsePilotCSV(PILOT_HEADERS.join(',')+'\n'));assert.equal(s.status,'not_run');assert.equal(s.overall.meanGainOutOf3,null);assert.equal(s.overall.completionRate,null);});
test('paired gain excludes missing observations rather than scoring them zero',()=>{const s=summarizePilot([observation('P001'),observation('P002',{post_year:'',duration_seconds:'',clarity_1_5:'',completed:'no'})]);assert.equal(s.overall.pairedScores,1);assert.equal(s.overall.meanGainOutOf3,2);assert.equal(s.overall.completed,1);assert.equal(s.overall.durationCount,1);assert.equal(s.overall.clarityCount,1);});
test('variants keep their denominators and do not infer learning from completion',()=>{const s=summarizePilot([observation('P001'),observation('P002',{variant:'fixed',post_year:'0',post_deadline:'0'})]);assert.equal(s.variants.adaptive.meanGainOutOf3,2);assert.equal(s.variants.fixed.meanGainOutOf3,0);assert.equal(s.overall.meanGainOutOf3,1);});
test('identifiers, consent and scores cannot silently corrupt a report',()=>{for(const rows of [[observation('P001'),observation('P001')],[observation('a name')],[observation('P001',{consent_recorded:'no'})],[observation('P001',{pre_year:'2'})],[{...observation('P001'),email:'a@example.invalid'}]])assert.throws(()=>summarizePilot(rows));});
test('CSV supports quoted cells and CRLF but rejects arbitrary text fields and malformed quoting',()=>{const header=PILOT_HEADERS.join(',');const row=PILOT_HEADERS.map(h=>'"'+observation('P001')[h]+'"').join(',');assert.equal(parsePilotCSV('\uFEFF'+header+'\r\n'+row+'\r\n')[0].participant_id,'P001');assert.throws(()=>parsePilotCSV(header+'\n"unclosed'));assert.throws(()=>parsePilotCSV('name,email\nA,B'));assert.throws(()=>parsePilotCSV(header+'\n'+row.replace('"P001"','"P001"x')));});
